# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EdgeTts < Formula
  desc "Edge TTS is a command-line tool based on Microsoft Edge's text-to-speech service"
  homepage "https://github.com/bytectlgo/edge-tts"
  version "1.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.4/edge-tts_Darwin_x86_64.tar.gz"
      sha256 "6bcc2ccba1369461f526a8981d92887b40d9413c5fad49a179d70d99fb65a459"

      def install
        bin.install "edge-tts"
      end
    end
    on_arm do
      url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.4/edge-tts_Darwin_arm64.tar.gz"
      sha256 "a1a7dec0900a7b5b7a6115e56074a6f2cb4246942c7606aedea3ce5f03d4c83c"

      def install
        bin.install "edge-tts"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.4/edge-tts_Linux_x86_64.tar.gz"
        sha256 "289068e40ff75a4eba723e74082da78740b1eaee97c5c2bc88e909eea79dc664"

        def install
          bin.install "edge-tts"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.4/edge-tts_Linux_arm64.tar.gz"
        sha256 "6707e71606c3f99fd1cb6ed72b771a082e0c681b2e68f5ba4b6ce654b0aa29a2"

        def install
          bin.install "edge-tts"
        end
      end
    end
  end
end
