# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EdgeTts < Formula
  desc "Edge TTS is a command-line tool based on Microsoft Edge's text-to-speech service"
  homepage "https://github.com/bytectlgo/edge-tts"
  version "1.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.3/edge-tts_Darwin_x86_64.tar.gz"
      sha256 "7451539b61ae3ddff261bda78b8379fedc8b93fbc0390f406b1816e1a70e0415"

      def install
        bin.install "edge-tts"
      end
    end
    on_arm do
      url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.3/edge-tts_Darwin_arm64.tar.gz"
      sha256 "078381fda6a700fbeae327977cbcf0a57997a4efd405e4eec5b8273761489cc3"

      def install
        bin.install "edge-tts"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.3/edge-tts_Linux_x86_64.tar.gz"
        sha256 "70a75d6e3f09bdb13d65bd81a1eb8871a8fdcc3dfbcb9342e57d186fcceb675c"

        def install
          bin.install "edge-tts"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.3/edge-tts_Linux_arm64.tar.gz"
        sha256 "aad61c93a990efadca6c7969952eeb010249a2a1307e643a6afae44b13fb5bca"

        def install
          bin.install "edge-tts"
        end
      end
    end
  end
end
