# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EdgeTts < Formula
  desc "Edge TTS is a command-line tool based on Microsoft Edge's text-to-speech service"
  homepage "https://github.com/bytectlgo/edge-tts"
  version "1.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.2/edge-tts_Darwin_x86_64.tar.gz"
      sha256 "7372e2fad9ef0399de2ff497117c041a348f7f84af2d84d11cf71169b0fa59a4"

      def install
        bin.install "edge-tts"
      end
    end
    on_arm do
      url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.2/edge-tts_Darwin_arm64.tar.gz"
      sha256 "1adc08e9396b59978f935e0076dd1e121677f4dc7fded363e05206d1d1d6f668"

      def install
        bin.install "edge-tts"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.2/edge-tts_Linux_x86_64.tar.gz"
        sha256 "a1c7efac6e8168402b6d1ffd282f9e41245ed3e135280346a0df4e3b12d27002"

        def install
          bin.install "edge-tts"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/edge-tts/releases/download/v1.0.2/edge-tts_Linux_arm64.tar.gz"
        sha256 "fbe6e749373b161b3984b0898c6a86773101a1931136b38d98a7e2c07157b0b9"

        def install
          bin.install "edge-tts"
        end
      end
    end
  end
end
