# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTool < Formula
  desc "A weather query MCP tool"
  homepage "https://github.com/bytectlgo/mcp_tool"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bytectlgo/mcp_tool/releases/download/v1.0.0/mcp_tool_Darwin_x86_64.tar.gz"
      sha256 "1cd1d597ee4770df922cf65ece0bf8b84a3fb340737f3af8f41a77fb18492f59"

      def install
        bin.install "weather_mcp"
      end
    end
    on_arm do
      url "https://github.com/bytectlgo/mcp_tool/releases/download/v1.0.0/mcp_tool_Darwin_arm64.tar.gz"
      sha256 "1071e730c4e5474e5dbb7c727fb0d43bd1d01a6c8f6a2af927c3894a58cf8e51"

      def install
        bin.install "weather_mcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/mcp_tool/releases/download/v1.0.0/mcp_tool_Linux_x86_64.tar.gz"
        sha256 "a99c84392e539b0692b414e5927e45126a3b21032d793f27fa944a66c2de8973"

        def install
          bin.install "weather_mcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/mcp_tool/releases/download/v1.0.0/mcp_tool_Linux_arm64.tar.gz"
        sha256 "ac7d366064396d4c8b3d52c887e39a514410859c4c653710b0214b83a281906e"

        def install
          bin.install "weather_mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/weather_mcp", "--version"
  end
end
