# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mem0 < Formula
  desc "A memory management tool"
  homepage "https://github.com/bytectlgo/mem0-go"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bytectlgo/mem0-go/releases/download/v1.0.0/mem0-go_Darwin_x86_64.tar.gz"
      sha256 "60f1d015313c4656c6c4b64baae014de0bb04eef76a4e6a99936eadae05155eb"

      def install
        bin.install "mem0"
      end
    end
    on_arm do
      url "https://github.com/bytectlgo/mem0-go/releases/download/v1.0.0/mem0-go_Darwin_arm64.tar.gz"
      sha256 "1efa4c56d016a590a0afe7ee9766447e4fe9380ce8636e10fd4db46b8ddf8a3c"

      def install
        bin.install "mem0"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/mem0-go/releases/download/v1.0.0/mem0-go_Linux_x86_64.tar.gz"
        sha256 "26ea49f29e454ac8034e76a42fcebccee6d9ae0be6ca58d13aec8cd7f1aa9149"

        def install
          bin.install "mem0"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bytectlgo/mem0-go/releases/download/v1.0.0/mem0-go_Linux_arm64.tar.gz"
        sha256 "af9274d819fef1c77b9979d1bd770073cd1fa85a833a1bd9362419f874743c5c"

        def install
          bin.install "mem0"
        end
      end
    end
  end

  test do
    system "#{bin}/mem0", "--version"
  end
end
